from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button
import os

class WattToAmpConverter(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(orientation='vertical', **kwargs)

        self.add_widget(Label(text="Enter Power (Watt):"))
        self.watt_input = TextInput(multiline=False)
        self.add_widget(self.watt_input)

        self.add_widget(Label(text="Enter Voltage (Volt):"))
        self.voltage_input = TextInput(multiline=False)
        self.add_widget(self.voltage_input)

        self.result_label = Label(text="Current (Amp): ")
        self.add_widget(self.result_label)

        self.convert_button = Button(text="Convert")
        self.convert_button.bind(on_press=self.convert)
        self.add_widget(self.convert_button)

    def convert(self, instance):
        try:
            watt = float(self.watt_input.text)
            voltage = float(self.voltage_input.text)
            if voltage == 0:
                self.result_label.text = "Error: Voltage cannot be zero"
            else:
                current = watt / voltage
                self.result_label.text = f"Current: {current:.2f} A"
        except ValueError:
            self.result_label.text = "Error: Enter valid numbers"

class WattToAmpApp(App):
    def build(self):
        return WattToAmpConverter()

if __name__ == "__main__":
    os.environ['KIVY_METRICS_DENSITY'] = '2'
    os.environ['KIVY_METRICS_DPI'] = '320'
    WattToAmpApp().run()
